### PR TITLE
Empirical Universe Machine Fits

### PR DESCRIPTION
**Pull request by cgannonucm**
feat: Added a nodeOperator implementing universe machine fits.

### CODE REVIEW

**Comment by abensonca** [comment]
For me, the test currently fails:
```
Traceback (most recent call last):
  File "/home/abenson/Galacticus/galacticus_Roman/testSuite/./test-UniverseMachine.py", line 156, in <module>
    assert_allclose(massStellar[isIsolated], massStellarPython)
  File "/carnegie/hpcdata/software/conda/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/carnegie/hpcdata/software/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/carnegie/hpcdata/software/conda/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 5 / 5 (100%)
Max absolute difference: 3.17475172e+09
Max relative difference: 0.00900385
 x: array([3.644063e+08, 4.042809e+06, 2.236959e+10, 3.494245e+11,
       1.132236e+11])
 y: array([3.643266e+08, 4.042772e+06, 2.232406e+10, 3.525993e+11,
       1.136963e+11])
```

Do we need to set a larger tolerance here, `rtol=0.01` maybe?

**Comment by cgannonucm** [comment]
> For me, the test currently fails:
> 
> ```
> Traceback (most recent call last):
>   File "/home/abenson/Galacticus/galacticus_Roman/testSuite/./test-UniverseMachine.py", line 156, in <module>
>     assert_allclose(massStellar[isIsolated], massStellarPython)
>   File "/carnegie/hpcdata/software/conda/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
>     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
>   File "/carnegie/hpcdata/software/conda/lib/python3.10/contextlib.py", line 79, in inner
>     return func(*args, **kwds)
>   File "/carnegie/hpcdata/software/conda/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError: 
> Not equal to tolerance rtol=1e-07, atol=0
> 
> Mismatched elements: 5 / 5 (100%)
> Max absolute difference: 3.17475172e+09
> Max relative difference: 0.00900385
>  x: array([3.644063e+08, 4.042809e+06, 2.236959e+10, 3.494245e+11,
>        1.132236e+11])
>  y: array([3.643266e+08, 4.042772e+06, 2.232406e+10, 3.525993e+11,
>        1.136963e+11])
> ```
> 
> Do we need to set a larger tolerance here, `rtol=0.01` maybe?

Yes it's failing for me as well too. I wanted to see if I could find the source of the difference because 0.01 seems quite large for a rounding error. Could it have something to do with timesteps?

**Comment by abensonca** [comment]
I think it's just that the UniverseMachine parameter values are specified with less precision in`test-UniverseMachine.xml` than in `test-UniverseMachine.py`. When I match them, the result agree perfectly.

I'll push up the updated file, along with the integration into the automated tests.

**Comment by cgannonucm** [comment]
Good catch! I copied and pasted the parameters over to ensure an exact match, but I must have cut off the final decimal points on some of the parameters when formatting. I would like to go ahead and add tests over multiple redshifts as well.

**Comment by abensonca** [comment]
Sounds good!

**Review by abensonca — APPROVED** [review]
I made a couple changes:

1.  I made it so that the disk/spheroid is initialized only in the node at the tip of the main branch - not all the way along the main branch.
2. I added some validation of the disk/spheroid fractions (sum to 1, non-negative).
3. I changed the logic for the `hasDisk` and `hasSpheroid` properties:
```diff
-    self%hasDisk            =fractionMassDisk     >= 0.0d0
-    self%hasSpheroid        =fractionMassSpheroid >= 0.0d0
+    self%hasDisk            =fractionMassDisk     >  0.0d0
+    self%hasSpheroid        =fractionMassSpheroid >  0.0d0
```
otherwise a zero fraction would still lead to the component being created.

With those changes, this all looks good.

**Pull request merged**
